[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openapi_mcp_etapi_518d0db5"
version = "0.1.0"
description = "MCP Server for ETAPI"
requires-python = ">=3.10"