name: Create Release Artifacts

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.0.1, etc.

jobs:
  build_and_upload_artifacts:
    name: Build and Upload Distribution Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # You can specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Clean dist directory
        run: rm -rf dist
      - name: Build distribution archives
        run: python setup.py sdist bdist_wheel

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
